version: 2.0
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: quay.io/haskell_works/stack-build-cabal:2018-05-31

    steps:
      - checkout

      ##### Copying scripts
      - run:
          name: Copying scripts
          command: |
            mkdir -p ~/.local/bin
            cp ./scripts/* ~/.local/bin

      - run:
          name: Delete cabal files & query resolver & ghc version
          command: |
            rm -f *.cabal
            resolver > resolver.conf
            ghc-version $(cat resolver.conf) >  ghc-version.conf

      ##### Updating cabval package list
      - run:
          name: Updating cabal package list date stamp
          command: date +%F > dot-cabal-cache-date

      - restore_cache:
          keys:
            - dot-cabal-{{ checksum "dot-cabal-cache-date" }}-gz8vvsw
            - dot-cabal

      - run:
          name: Updating cabal package list
          command: cabal update

      - save_cache:
          key: dot-cabal-{{ checksum "dot-cabal-cache-date" }}-gz8vvsw
          paths:
            - ~/.cabal
      - save_cache:
          key: dot-cabal
          paths:
            - ~/.cabal

      - restore_cache:
          keys:
            - dot-stack-{{ checksum "stack.yaml"         }}-{{ checksum "package.yaml" }}-gz8vvsw
            - dot-stack-{{ checksum "resolver.conf"      }}-build-gz8vvsw
            - dot-stack-{{ checksum "ghc-version.conf"   }}-build-gz8vvsw
            - dot-stack-{{ checksum "resolver.conf"      }}-setup-gz8vvsw
            - dot-stack-{{ checksum "ghc-version.conf"   }}-setup-gz8vvsw

      - run:
          name: Fetching latest organisation package versions
          command: |
            fetch
            echo "== stack-ci.yaml =="
            cat stack-ci.yaml

      - restore_cache:
          keys:
            - dot-stack-work-{{ checksum "resolver.conf"      }}-gz8vvsw
            - dot-stack-work-{{ checksum "ghc-version.conf"   }}-gz8vvsw

      - run:
          name: Stack setup
          command: stack setup

      - save_cache:
          key:    dot-stack-{{ checksum "resolver.conf"      }}-setup-gz8vvsw
          paths:  ~/.stack
      - save_cache:
          key:    dot-stack-{{ checksum "ghc-version.conf"   }}-setup-gz8vvsw
          paths:  ~/.stack

      - run:
          name: Building dependencies
          command: stack --stack-yaml stack-ci.yaml build --only-dependencies

      - run:
          name: Compiling
          command: stack --stack-yaml stack-ci.yaml build --test --no-run-tests --bench --no-run-benchmarks

      - save_cache:
          key:    dot-stack-{{ checksum "stack.yaml"         }}-{{ checksum "package.yaml" }}-gz8vvsw
          paths:  ~/.stack
      - save_cache:
          key:    dot-stack-{{ checksum "resolver.conf"      }}-build-gz8vvsw
          paths:  ~/.stack
      - save_cache:
          key:    dot-stack-{{ checksum "ghc-version.conf"   }}-build-gz8vvsw
          paths:  ~/.stack
      - save_cache:
          key:    dot-stack-work-{{ checksum "resolver.conf" }}-gz8vvsw
          paths:  ~/project/.stack-work

      ##### Running tests
      - run:
          name: Running tests against latest on hackage
          command: stack --stack-yaml stack-ci.yaml test

      - deploy:
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" == "haskell-works" ]; then
              if [[ "$CIRCLE_BRANCH" == master ]]; then
                when tag autotag
              elif [[ "$CIRCLE_TAG" =~ v.* ]]; then
                publish
              fi
            fi
deployment:
  tagged_builds:
    tag: /v.*/
    commands:
      - echo "Make tags run in 2.0"
